### ISSUE TITLE
【无法运行】No module named 'nonebot.adapters.onebot.v11.exception'

### ISSUE THREAD

**Issue by Z735803792** [yzyyz1387/nonebot_plugin_admin#22]
python3.9.12
nonebot2.0.0b4
nonebot-adapter-onebot=2.1.0
其他依赖均无问题

启动时终端如下，可能并不能适配nonebot2.0.0b4
![image](https://user-images.githubusercontent.com/70925546/177465778-e6599bc9-2230-4b3e-9cdc-ad18d31ef292.png)

**Comment by yzyyz1387** [comment]
是还没适配，你可以用ide搜索所有的
```
from nonebot.adapters.nonebot.v11.exception import ActionFailed
```
这一句，改成
```
from nonebot.adapters.nonebot.exceotion import ActionFailed
```

**Comment by Kiana1314** [comment]
请问是所有.py文件都要改吗。我还是报错啊

**Comment by yzyyz1387** [comment]
> 请问是所有.py文件都要改吗。我还是报错啊

。。。。

**Comment by yzyyz1387** [comment]
> 请问是所有.py文件都要改吗。我还是报错啊

那必然是的

**Comment by Kiana1314** [comment]
![J(WPV_(GO3MUQ(YH$PXK6FP](https://user-images.githubusercontent.com/107671434/177918550-26ace616-5994-44e9-b8d5-a86662bae1a7.png)

**Comment by yzyyz1387** [comment]
> ![J(WPV_(GO3MUQ(YH$PXK6FP](https://user-images.githubusercontent.com/107671434/177918550-26ace616-5994-44e9-b8d5-a86662bae1a7.png)

上面回复你的写错了 o 换成 p

**Comment by Kiana1314** [comment]
启动无报错  发送群管初始化后跳出了这个 
![V$A`MN78RXB%Q1O OVNICO1](https://user-images.githubusercontent.com/107671434/177962389-d910f28e-f819-4f38-a592-334fe435ca73.png
另外 请问改头衔指令是不是只有bot为群主时才有用？

**Comment by Kiana1314** [comment]
启动无报错 发送群管初始化后跳出了这个
![V$A`MN78RXB%Q1O OVNICO1](https://user-images.githubusercontent.com/107671434/177963691-95c6c198-f8d9-4219-87d5-c612a4ce4a18.png)

另外 请问改头衔指令是不是只有bot为群主时才有用？

**Comment by yzyyz1387** [comment]
> 启动无报错 发送群管初始化后跳出了这个
> ![V$A`MN78RXB%Q1O OVNICO1](https://user-images.githubusercontent.com/107671434/177963691-95c6c198-f8d9-4219-87d5-c612a4ce4a18.png)
> 
> 另外 请问改头衔指令是不是只有bot为群主时才有用？

问题一不清楚应该不影响使用，最近较忙没时间看，github的发布都是「dev」向的，也就是说正在开发中，后续会一直优化，所以追求稳定的话用pypi的版本

问题二，就算不用机器人，也只有群主能设置头衔

**Comment by Kiana1314** [comment]
好的谢谢  大佬辛苦了

**Comment by yzyyz1387** [comment]
> 好的谢谢 大佬辛苦了

没事，祝愉快![](https://api.isoyu.com/uploads/ARU/GIF_S/6020.gif)

**Comment by nanxu2019** [comment]
07-17 21:07:44 [ERROR] nonebot | Running matcher <Matcher from nonebot_plugin_admin.auto_ban, type=message, priority=0,
temp=False> failed.
Traceback (most recent call last):
 File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\nonebot_plugin_admin\utils.py",
line 374, in check_func_status
    if funcs_status[gid][func_name]:
KeyError: '580798311'
群管初始化后会一直报错诶

**Comment by yzyyz1387** [comment]
> 07-17 21:07:44 [ERROR] nonebot | Running matcher <Matcher from nonebot_plugin_admin.auto_ban, type=message, priority=0, temp=False> failed. Traceback (most recent call last): File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\nonebot_plugin_admin\utils.py", line 374, in check_func_status if funcs_status[gid][func_name]: KeyError: '580798311' 群管初始化后会一直报错诶

看起来是旧版代码，换仓库的版本吧，还有，你怎么在issue里面提issue

**Comment by nanxu2019** [comment]
用的你github仓库教程重装的，还是这样，应该不是旧版本原因。可能是我初始化插件后才加新群的缘故，我手动改下配置好了对于在issue里面提issue抱歉，嘿嘿嘿，主要顺手就提了





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月17日(星期天) 晚上9:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yzyyz1387/nonebot_plugin_admin] 【无法运行】No module named &#39;nonebot.adapters.onebot.v11.exception&#39; (Issue #22)





  
07-17 21:07:44 [ERROR] nonebot | Running matcher <Matcher from nonebot_plugin_admin.auto_ban, type=message, priority=0, temp=False&gt; failed. Traceback (most recent call last): File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\nonebot_plugin_admin\utils.py", line 374, in check_func_status if funcs_status[gid][func_name]: KeyError: '580798311' 群管初始化后会一直报错诶
  
看起来是旧版代码，换仓库的版本吧，还有，你怎么在issue里面提issue

**Comment by yzyyz1387** [comment]
> 用的你github仓库教程重装的，还是这样，应该不是旧版本原因。可能是我初始化插件后才加新群的缘故，我手动改下配置好了对于在issue里面提issue抱歉，嘿嘿嘿，主要顺手就提了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年7月17日(星期天) 晚上9:19 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [yzyyz1387/nonebot_plugin_admin] 【无法运行】No module named &#39;nonebot.adapters.onebot.v11.exception&#39; (Issue #22) 07-17 21:07:44 [ERROR] nonebot | Running matcher <Matcher from nonebot_plugin_admin.auto_ban, type=message, priority=0, temp=False&gt; failed. Traceback (most recent call last): File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\nonebot_plugin_admin\utils.py", line 374, in check_func_status if funcs_status[gid][func_name]: KeyError: '580798311' 群管初始化后会一直报错诶 看起来是旧版代码，换仓库的版本吧，还有，你怎么在issue里面提issue — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

374行明显不是`check_func_status`
https://github.com/yzyyz1387/nonebot_plugin_admin/blob/main/nonebot_plugin_admin/utils.py#L374

**Comment by nanxu2019** [comment]
使用旧代码可能是使用命令安装的缘故
但又出现了新的问题&nbsp;
&nbsp;File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\nonebot_plugin_admin\utils.py",
line 37, in <module&gt;
&nbsp; &nbsp; def At(data: str) -&gt; Union[list[str], list[int], list]:
TypeError: 'type' object is not subscriptable





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yzyyz1387/nonebot_plugin_admin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月17日(星期天) 晚上9:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yzyyz1387/nonebot_plugin_admin] 【无法运行】No module named 'nonebot.adapters.onebot.v11.exception' (Issue #22)





  
用的你github仓库教程重装的，还是这样，应该不是旧版本原因。可能是我初始化插件后才加新群的缘故，我手动改下配置好了对于在issue里面提issue抱歉，嘿嘿嘿，主要顺手就提了
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2022年7月17日(星期天) 晚上9:19 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [yzyyz1387/nonebot_plugin_admin] 【无法运行】No module named 'nonebot.adapters.onebot.v11.exception' (Issue #22) 07-17 21:07:44 [ERROR] nonebot | Running matcher <Matcher from nonebot_plugin_admin.auto_ban, type=message, priority=0, temp=False&gt; failed. Traceback (most recent call last): File "c:\users\administrator\appdata\local\programs\python\python38\lib\site-packages\nonebot_plugin_admin\utils.py", line 374, in check_func_status if funcs_status[gid][func_name]: KeyError: '580798311' 群管初始化后会一直报错诶 看起来是旧版代码，换仓库的版本吧，还有，你怎么在issue里面提issue — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
374行明显不是check_func_status
 https://github.com/yzyyz1387/nonebot_plugin_admin/blob/main/nonebot_plugin_admin/utils.py#L374

**Comment by ria-klee** [comment]
谢谢~
